### ISSUE TITLE
package is not available at pypi.org

### ISSUE THREAD

**Issue by x0day** [cloud-custodian/cel-python#13]
currently, package is not available at pypi.org.
so what's the release date?

**Comment by slott56** [comment]
We don't have a concrete plan (yet.) Currently, for example, there's no protobuf support, a huge gap.

The question suggests we really *should* have some kind of plan for that. Thanks for raising it.

**Comment by dcharbon** [comment]
I'd like to register interest in having this on pypi sooner rather than later. I'm moving ahead to adopt in two projects where this is an ideal fit, no need for protobuf suport. 

[django-scoped-rbac)[https://gitlab.com/openteams/django-scoped-rbac]
    CEL is a perfect fit for conditional policy expressions for access control.

[scrud-django](https://gitlab.com/openteams/scrud-django)
    CEL policy expressions make a great way of defining "state" in a workflow for validation and access control.

**Comment by slott56** [comment]
I'm hoping to add some folks to the project who can help with things like PyPI deployment and acceptance testing.

**Comment by kapilt** [comment]
i can have a look at copying over some of our release automation from c7n repo, although its pretty minimal. @slott56 what's your pypi username?

**Comment by slott56** [comment]
https://pypi.org/user/slott/

**Comment by kylejohnson514** [comment]
Bumping this now after Steven's protobuf work has been merged into master. Has anyone started the work to publish this to PyPI? If not, I can look into it

**Comment by kylejohnson514** [comment]
https://pypi.org/project/cel-python/ is now available! I'd like to look into some release automation, but for now, I manually pushed it up

**Comment by kapilt** [comment]
thanks @kylejohnson514 please ensure both slott and myself (kapilt) have full access to the package in pypi.
