### ISSUE TITLE
Add support for type checking (PEP 561)

### ISSUE THREAD

**Issue by kirill-gr** [cloud-custodian/cel-python#39]
Currently running mypy checks against code, that is using celpy, results in the following output:

> error: Skipping analyzing "celpy": module is installed, but missing library stubs or py.typed marker  [import]
> note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
> error: Type of variable becomes "Any" due to an unfollowed import  [no-any-unimported]

This can be fixed by adding `py.typed` file (https://peps.python.org/pep-0561/#packaging-type-information). I've tried adding it locally to the celpy package and mypy checks have passed.

**Comment by kapilt** [comment]
Pull request welcome
